import type { CanutoEvent } from "../types";

function hoursFromNow(h: number) {
  return new Date(Date.now() + h * 60 * 60 * 1000).toISOString();
}

function daysFromNow(d: number, hour = 20) {
  const date = new Date();
  date.setDate(date.getDate() + d);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

/** Seed events around Córdoba Capital for local/demo mode */
export const SEED_EVENTS: CanutoEvent[] = [
  {
    id: "seed-1",
    title: "Ciclo de circo en Parque Las Heras",
    description: "Circo al aire libre. Entrada libre, salida a la gorra.",
    event_type: "infantil",
    starts_at: hoursFromNow(2),
    ends_at: hoursFromNow(4),
    lat: -31.4295,
    lng: -64.1882,
    address: "Parque Las Heras",
    cost_type: "a_la_gorra",
    price: null,
    visibility: "public",
    status: "approved",
    source: "scrape",
    source_url: "https://cultura.cordoba.gob.ar/agenda/#circo",
    source_name: "Cultura Municipal",
    cover_url: "https://images.unsplash.com/photo-1503095396549-807759245b35?w=1200&q=80",
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-2",
    title: "Juan Falú en Teatro Comedia",
    description: "Guitarra, canciones y palabras.",
    event_type: "musica",
    starts_at: daysFromNow(1, 20),
    ends_at: daysFromNow(1, 22),
    lat: -31.4167,
    lng: -64.1833,
    address: "Teatro Comedia",
    cost_type: "pago",
    price: 25000,
    visibility: "public",
    status: "approved",
    source: "scrape",
    source_url: "https://cultura.cordoba.gob.ar/agenda/#falu",
    source_name: "Cultura Municipal",
    cover_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&q=80",
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-3",
    title: "Muestra «Luz contemporánea»",
    description: "Museo Juan de Tejeda.",
    event_type: "exposicion",
    starts_at: hoursFromNow(5),
    ends_at: hoursFromNow(8),
    lat: -31.4189,
    lng: -64.1865,
    address: "Museo Juan de Tejeda",
    cost_type: "pago",
    price: 3000,
    visibility: "public",
    status: "approved",
    source: "scrape",
    source_url: "https://cultura.cordoba.gob.ar/agenda/#luz",
    source_name: "Cultura Municipal",
    cover_url: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-4",
    title: "Cineclub Municipal",
    description: "Proyección de la tarde.",
    event_type: "cine",
    starts_at: hoursFromNow(1.5),
    ends_at: hoursFromNow(3.5),
    lat: -31.4215,
    lng: -64.1871,
    address: "Blvd. San Juan 49",
    cost_type: "gratis",
    price: null,
    visibility: "public",
    status: "approved",
    source: "scrape",
    source_url: "https://cultura.cordoba.gob.ar/agenda/#cine",
    source_name: "Cultura Municipal",
    cover_url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&q=80",
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-5",
    title: "Feria Sabores y Dulzuras",
    description: "Productores locales.",
    event_type: "feria",
    starts_at: daysFromNow(3, 16),
    ends_at: daysFromNow(3, 21),
    lat: -31.4192,
    lng: -64.1888,
    address: "Ex Plaza Vélez Sarsfield",
    cost_type: "gratis",
    price: null,
    visibility: "public",
    status: "approved",
    source: "scrape",
    source_url: "https://cultura.cba.gov.ar/eventos/#feria",
    source_name: "Agencia Córdoba Cultura",
    cover_url: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-6",
    title: "Peña en Güemes",
    description: "Música en vivo.",
    event_type: "musica",
    starts_at: daysFromNow(5, 21),
    ends_at: daysFromNow(5, 23),
    lat: -31.425,
    lng: -64.19,
    address: "Barrio Güemes",
    cost_type: "a_la_gorra",
    price: null,
    visibility: "public",
    status: "approved",
    source: "organizer",
    source_url: null,
    source_name: null,
    cover_url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&q=80",
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-7",
    title: "Partido amateur — Kempes",
    description: "Amistoso al aire libre.",
    event_type: "deporte",
    starts_at: daysFromNow(10, 18),
    ends_at: daysFromNow(10, 20),
    lat: -31.3688,
    lng: -64.246,
    address: "Predio Kempes",
    cost_type: "gratis",
    price: null,
    visibility: "public",
    status: "approved",
    source: "organizer",
    source_url: null,
    source_name: null,
    cover_url: null,
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "seed-8",
    title: "Muestra de agosto — Caraffa",
    description: "Arte contemporáneo.",
    event_type: "exposicion",
    starts_at: daysFromNow(25, 11),
    ends_at: daysFromNow(25, 18),
    lat: -31.4275,
    lng: -64.185,
    address: "Museo Caraffa",
    cost_type: "pago",
    price: 2000,
    visibility: "public",
    status: "approved",
    source: "scrape",
    source_url: "https://cultura.cordoba.gob.ar/agenda/#caraffa",
    source_name: "Cultura Municipal",
    cover_url: "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=1200&q=80",
    created_by: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
